### ISSUE TITLE
compilation error - specified bound 128 equals destination size [-Werror=stringop-overflow=] (GCC 10.2.1)

### ISSUE THREAD

**Issue by Nindaleth** [Try/OpenGothic#114]
Introduced in 9155e408, reported by ccache'd GCC 10.2.1 on Linux. Silencing this one allows me to build fully, there should be no other issue.

```
/home/black_fox/src/OpenGothic/Game/resources.cpp: In static member function ‘static std::vector<const Tempest::Texture2d*> Resources::loadTextureAnim(const string&)’:
/home/black_fox/src/OpenGothic/Game/resources.cpp:595:14: error: ‘char* strncat(char*, const char*, size_t)’ specified bound 128 equals destination size [-Werror=stringop-overflow=]
  595 |       strncat(buf,".TGA",sizeof(buf));
      |       ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Try** [comment]
Looks like gcc 10 is way to strict about c-strings :D 

Actually me start to think about move from `const char*` to something else. May be create Str128, or even Str64 to address files in *.vdf archives.
