### ISSUE TITLE
Failure building latest master

### ISSUE THREAD

**Issue by Newbytee** [Try/OpenGothic#148]
After following the instructions on how to build for Linux I'm greeted by this error:
```
[ 75%] Building CXX object CMakeFiles/Gothic2Notr.dir/game/camera.cpp.o
In file included from /mnt/storage/Programming/opengothic-2/game/camera.cpp:3:
/mnt/storage/Programming/opengothic-2/game/world/objects/npc.h:3:10: fatal error: graphics/mesh/pose.h: No such file or directory
    3 | #include "graphics/mesh/pose.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Gothic2Notr.dir/build.make:108: CMakeFiles/Gothic2Notr.dir/game/camera.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:565: CMakeFiles/Gothic2Notr.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
Building v0.37 works fine. Reverting https://github.com/Try/OpenGothic/commit/1399b1157dd4d754a41698bc210490b0407fb26c fixes this.

**Comment by Newbytee** [comment]
Reverting 1399b1157dd4d754a41698bc210490b0407fb26c fixes this, but then I get another error:

```
[ 78%] Building CXX object CMakeFiles/Gothic2Notr.dir/Game/camera.cpp.o
In file included from /mnt/storage/Programming/OpenGothic/Game/world/objects/npc.h:5,
                 from /mnt/storage/Programming/OpenGothic/Game/camera.cpp:3:
/mnt/storage/Programming/OpenGothic/Game/graphics/meshobjects.h:5:10: fatal error: Tempest/DescriptorSet: No such file or directory
    5 | #include <Tempest/DescriptorSet>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Gothic2Notr.dir/build.make:108: CMakeFiles/Gothic2Notr.dir/Game/camera.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:563: CMakeFiles/Gothic2Notr.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
