### ISSUE TITLE
compilation error: ‘.TGA’ directive output may be truncated writing 4 bytes into a region of size between 1 and 128 [-Werror=format-truncation=] (GCC 10.2.0-4)

### ISSUE THREAD

**Issue by py7hon** [Try/OpenGothic#116]
I have a error log while compile on Archlinux with GCC 10.2.0-4.
```shell
/home/arch/OpenGothic/Game/resources.cpp: In static member function ‘static std::vector<const Tempest::Texture2d*> Resources::loadTextureAnim(const string&)’:
/home/arch/OpenGothic/Game/resources.cpp:570:41: error: ‘.TGA’ directive output may be truncated writing 4 bytes into a region of size between 1 and 128 [-Werror=format-truncation=]
  570 |       std::snprintf(buf2,sizeof(buf),"%s.TGA",buf);
      |                                         ^~~~
/home/arch/OpenGothic/Game/resources.cpp:570:20: note: ‘snprintf’ output between 5 and 132 bytes into a destination of size 128
  570 |       std::snprintf(buf2,sizeof(buf),"%s.TGA",buf);
      |       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/Gothic2Notr.dir/build.make:1187: CMakeFiles/Gothic2Notr.dir/Game/resources.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:563: CMakeFiles/Gothic2Notr.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**Comment by py7hon** [comment]
still same got error 
```
/home/arch/OpenGothic/Game/resources.cpp: In static member function ‘static std::vector<const Tempest::Texture2d*> Resources::loadTextureAnim(const string&)’:
/home/arch/OpenGothic/Game/resources.cpp:570:41: error: ‘.TGA’ directive output may be truncated writing 4 bytes into a region of size between 1 and 128 [-Werror=format-truncation=]
  570 |       std::snprintf(buf2,sizeof(buf),"%s.TGA",buf);
      |                                         ^~~~
/home/arch/OpenGothic/Game/resources.cpp:570:20: note: ‘snprintf’ output between 5 and 132 bytes into a destination of size 128
  570 |       std::snprintf(buf2,sizeof(buf),"%s.TGA",buf);
      |       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
after change on line `569`

**Comment by Nindaleth** [comment]
Isn't there something cached? After the code change, there is no "destination of size 128" after all.

**Comment by py7hon** [comment]
I cleared the cache, so I tried again and got an error
```
/home/arch/OpenGothic/Game/resources.cpp: In static member function ‘static std::vector<const Tempest::Texture2d*> Resources::loadTextureAnim(const string&)’:
/home/arch/OpenGothic/Game/resources.cpp:570:41: error: ‘.TGA’ directive output may be truncated writing 4 bytes into a region of size between 1 and 256 [-Werror=format-truncation=]
  570 |       std::snprintf(buf2,sizeof(buf),"%s.TGA",buf);
      |                                         ^~~~
/home/arc/OpenGothic/Game/resources.cpp:570:20: note: ‘snprintf’ output between 5 and 260 bytes into a destination of size 256
  570 |       std::snprintf(buf2,sizeof(buf),"%s.TGA",buf);
      |       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Try** [comment]
```c++
std::snprintf(buf2,sizeof(buf),"%s.TGA",buf);
                             ^
```
My bad. Anyway going to disable this warning at all: this warn is more harm than good.

**Comment by Nindaleth** [comment]
The current state fails for me like this:
```
/home/black_fox/src/OpenGothic/Game/resources.cpp: In static member function ‘static std::vector<const Tempest::Texture2d*> Resources::loadTextureAnim(const string&)’:
/home/black_fox/src/OpenGothic/Game/resources.cpp:569:20: error: ‘snprintf’ argument 4 overlaps destination object ‘buf’ [-Werror=restrict]
  569 |       std::snprintf(buf,sizeof(buf),"%s.TGA",buf);
      |       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/black_fox/src/OpenGothic/Game/resources.cpp:553:12: note: destination object referenced by ‘restrict’-qualified argument 1 was declared here
  553 |     char   buf[128]={};
      |            ^~~
```

I've returned the 2nd buffer `char buf2[256]={};` to the snprintf and that fixes compilation for me.

**Comment by Try** [comment]
@Nindaleth 
Looks like this is different warning (error actually):` snprintf` cannot use same buffer as output and input simultaneously.

I've reintroduce `buf2` in f81d3e5, everything else should be already covered by `-Wno-format-truncation` in CMakeLists.txt

**Comment by Nindaleth** [comment]
As far as my environment is concerned, everything compiles after the latest change :+1: Thanks!
